### ISSUE TITLE
Outline for a .php document

### ISSUE THREAD

**Issue by theodore-steiner** [Hirse/brackets-outline-list#112]
**Details about your environment**

* **Brackets Version: 1.13 ** 
* **Brackets Outline List Version:** 

**What did you do? Please include the actual source code causing the issue.**
I might have just missed this, but there seem to be no outline generated for .php files, is this normal? 

```

```

**What did you expect to happen? How did you expect the Outline to look?**

**What actually happened? How did the Outline actually look?**

**Comment by Hirse** [comment]
PHP is one of the supported languages. Files opened as PHP in Brackets are parsed for content.
As long as your file contains classes or functions, there should be an outline when the extension is turned on.

There could be an issue that only happens with your specific PHP-file, but without further information, there is nothing I can do.

**Comment by Hirse** [comment]
Closing due to missing information.
