### ISSUE TITLE
Support suggestion for Stylus

### ISSUE THREAD

**Issue by renanveroneze** [Hirse/brackets-outline-list#14]
I could not understand how to make a plugin for the Outline.
So, I opened this issue, as Stylus use, like to have the features as css.

Thanks =D

**Comment by Jonatthu** [comment]
Stylus and Jade are important now!(: Please how can we colaborate with you for do this real?

**Comment by Hirse** [comment]
For Stylus you could have a look at the [CSS outline module](https://github.com/Hirse/brackets-outline-list/blob/master/src/languages/CSS.js) and adapt it to the language.
Based on a first look at Stylus, it seems a bit complicated to parse as many things are optional and can be written in multiple ways. It would be fine by me if we only support one way for now, so for example either always require braces or always omit them. 

-
For Jade, probably the [HTML/XML outline module](https://github.com/Hirse/brackets-outline-list/blob/master/src/languages/XML.js) would work best as a starting point.
If I understand the language correctly (again based on a very quick glance on the example on their website), Jade mostly works with indentations. That would make creating an outline somewhat easier as the necessary regex should be simple.

**Comment by Jonatthu** [comment]
Okey, then, do you have facebook or something for chat and make this happen? I will help you with that, or some other idea?

**Comment by Hirse** [comment]
I have created the basic infrastructure for Jade and Stylus on a separate branch [jade/stylus](https://github.com/Hirse/brackets-outline-list/tree/jade/stylus).
Have a look at the test files that I used for reference and also at the js files creating the outline.
Please expand the logic and the regex if necessary.

**Comment by Hirse** [comment]
Merged in eb037261945d5d730bf171297f793a06d9aae9d0.
