### ISSUE TITLE
Suggestion for autohide

### ISSUE THREAD

**Issue by Jurigag** [Hirse/brackets-outline-list#17]
I have suggestion. Can you do something what is in [Sidebar Plus](https://github.com/sathyamoorthi/brackets-sidebar-plus)? I mean when i edit some file outline is hidden on right, but i can click on it when i want and select what i want and then when i click again in file to edit something and it hides again. As hidden i mean there are a small bar what you can expand. It could be awesome !

**Comment by Jurigag** [comment]
Any progress, i think it could be pretty nice.

**Comment by Hirse** [comment]
Not yet, as I was on vacation until Tuesday. But this is most likely the next thing I will look into.
In the meantime, feel free to try yourself and submit a PR if you like. :wink:
