### ISSUE TITLE
Extract problem

### ISSUE THREAD

**Issue by awakekat** [Hirse/brackets-outline-list#19]
I think your plugin is awesome, but...
It is causing Adobe Extract not to load properly. I uninstalled your plugin and the Extract plugin icon showed back up on the right tool bar. Have posted at Extract repo too.
FYI

**Comment by Hirse** [comment]
I am still unable to see this problem.
Since nobody else seems to have this and you seem to be unable to provide further information, I will close it for now.
Feel free to reopen when you experience this again.
