### ISSUE TITLE
top toolbar with dropdown

### ISSUE THREAD

**Issue by apla** [Hirse/brackets-outline-list#20]
Hi!

Can you add a top toolbar with outline dropdown?

**Comment by Hirse** [comment]
I am not entirely sure what you mean.
There is a dropdown in the topbar that you can use to jump to definitions:
![top bar](https://cloud.githubusercontent.com/assets/2564094/5695467/7538ba90-99a5-11e4-88a3-c38c5838c096.png)
You can open it with Ctrl + T.

**Comment by apla** [comment]
This is what I'm looking for! Thank you!
