### ISSUE TITLE
Display class name (especially with PHP)

### ISSUE THREAD

**Issue by partageit** [Hirse/brackets-outline-list#24]
Hello,
Thank you for this plugin, it is very useful :)

I have a request: when I work with PHP files, every methods are listed like functions.
It would be nice to display it under the class name (or near, or whatever).

David

**Comment by Hirse** [comment]
Looks like you have already found a solution. Great!
Do you care to submit a pull request so it can be shared with others?

**Comment by Hirse** [comment]
Should be solved with the addition of a Lexer for PHP.
Please install from the latest commit to see if it works for you.
