### ISSUE TITLE
Display error

### ISSUE THREAD

**Issue by Sean-Wang** [Hirse/brackets-outline-list#26]
![snip20150211_2](https://cloud.githubusercontent.com/assets/1193073/6144187/49747408-b20f-11e4-9da7-9d275a45d6ec.png)
![snip20150211_3](https://cloud.githubusercontent.com/assets/1193073/6144189/4bdabfd6-b20f-11e4-9857-9c2a4f092112.png)

Node.js, `queryPersonObjectID` is not a function, but brackets-outline-list also display in left window.

**Comment by Hirse** [comment]
Yes, `object.queryPersonObjectID` is a function just as `exports.deleteMaintenanceCompany`is. 
I agree that is doesn't really belong in the outline, but that can only be determined by the context, not by the syntax that the Regex uses to match function definitions.

Feel free to play around with the code of this extension. If you find a good solution, I would be happy to include it, but for me this is not something I am going to change.
