### ISSUE TITLE
JS Object properties that are functions

### ISSUE THREAD

**Issue by dwhogg** [Hirse/brackets-outline-list#27]
Would like to see in the outline list object (or perhaps just returned objects from a module?) properties that are functions.

Often modules will return an object of the form:
```javascript
    return {
       function1: function(foo) {
           _doStuff();
       },
      function2: _doStuff2
    };
```
At the moment, the function1 will appear in the outline, but not function2. Would be great to have both.
Loving this extension, BTW!

**Comment by Hirse** [comment]
Thank you. :smile: 

Unfortunately your request / wish is somewhat out of the scope of this extension as of now.
Currently I am using regular expressions on every line to check if this line contains a function definition and to extract the function name.
To display properties or variables that get assigned functions would require to do code analysis that is much more advanced than using pure text analysis.
While there are some possibilities to do that (as other extensions have shown) I have not found a solution that keeps the connection to the text and therefore the functionality to jump from the list to the line in the code.

In any case, the assignment `function2: _doStuff2` in your example is not a function declaration and I think that including this kind of assignments in the outline might make it too full.

That being said, if you find a solution that doesn't conflict with these requirements I am open to including it into the extension.

**Comment by dwhogg** [comment]
Makes sense. Thanks.
