### ISSUE TITLE
plugin can't list one method

### ISSUE THREAD

**Issue by canyavall** [Hirse/brackets-outline-list#33]
First of all, thank you very much for this useful plugin!!

i have some kind of issue when listing one of my classes, this class contains this method:
```php
public static function htmlSimplifyWord($text, $allowed_tags = '<h1><h2><h3><h4><h5><p><br><b><i><sub><sup><ul><ol><li>', $allowed_attributes = array('alt', 'href', 'title', 'rowspan', 'colspan', 'src', 'summary', 'class', 'id', 'name', 'title', 'target', 'nowrap', 'rel')) {}
```

This method is not listed in the plugin, I've copy pasted it in another classes and none could be listed.
I've seen the problem are the tags, removing them it works properly, just in case you need to know it!
Thank you for your work!

**Comment by Hirse** [comment]
Fixed in aa82ba393efbd3562ba730b32ae27f8fbf3a4f3b.
It is going to show static methods differently now as well.
I am also working on further features so I am going to update the extension once I finish that.
Feel free to test it before by installing from GitHub directly.
