### ISSUE TITLE
Does crash bracket with base64-encoding!

### ISSUE THREAD

**Issue by activenode** [Hirse/brackets-outline-list#37]
This plugin crashes brackets when using long base64-encoded images in e.g. an icons.css
Brackets version: Release 1.2 Build 1.2.0-15697 (release 8f82e2a97) 
System: OSX

**Comment by Hirse** [comment]
I have created a simple fix for this issue.
Could you please install the latest version of the extension from URL and let me know if it works?

**Comment by Obras** [comment]
Brackets still crashing if a long base64 encoded font is opened.
I've installed last version (0.5.1) of the extension, and when trying to open a CSS file with an url(data:application/x-font...) rule, a Brackets Helper goes to the 100% of CPU and Brackets become unresponsive.
Brackets version: 1.3 release 1.3.0-16022
Brackets Outline List version: 0.5.1
MacOSX Yosemite

**Comment by Hirse** [comment]
How did you install the extension?
This fix is not yet released on the extension registry. Could you please use the second installation approach as described [here](https://github.com/Hirse/brackets-outline-list#installation) and check if that fixes it?

**Comment by Obras** [comment]
Great, I used the URL installation and it seems the issue has gone.
Thanks a lot!

**Comment by Hirse** [comment]
Thanks for the feedback.
I am going to close this issue then.
