### ISSUE TITLE
Brackets crash after outline panel vertically resized.

### ISSUE THREAD

**Issue by septianw** [Hirse/brackets-outline-list#38]
Brackets version : Release 1.3 experimental build 1.3.0-16022 (release cd0a6aae5) 
build timestamp: Fri Apr 24 2015 05:29:46 GMT-0700
plugin version : 0.5.1
reproduce : Open Brackets outline panel and resize it vertically.

**Comment by septianw** [comment]
this is list of installed plugin of my brackets

Markdown Preview
Glenn Ruehle <gruehle@gmail.com> (http://github.com/gruehle)
1.0.9	 Live preview of markdown documents
   
Simple To-Do
Oleg Koshelnikov <koshelnikov@gmail.com>
0.1.2	 Simple to-do list for Brackets. Tasks stored in human readable/editable text files.
   
Themes for Brackets
Jacob Lauritzen <jacsebl@hotmail.com>
2.0.10	 The popular extension now works as a theme-pack that styles the whole editor!
   
Todo
Mikael Jorhult <mikael@jorhult.se> (http://jorhult.se)
0.8.0	 Display all TODO comments in current document or project.

Translated into 10 languages, including yours	   
Brackets Bookmarks
Ashutosh Sharma <ashutosh@adobe.com> (http://deceptiveweb.com)
1.0.1	 Navigate within a document using bookmarks. Cmd-F4 to toggle, F4 to jump to bookmarks.

Brackets Compare
Hubert Boma Manilla (http://www.bomsy.org)
0.0.1	 A diff tool for brackets

Brackets Darker
Amit Mendapara
3.2.0	 Darker interface & editor themes

Brackets Editor Bookmarks
Jeffry Booher|jsbooher@adobe.com (http://www.facebook.com/JeffryBooher)|@JeffryBooher
0.9.31	 Bookmark lines in the editor as you work so you can quickly jump back to them later. Open the "Bookmarks" Panel to see all of the bookmarks and open them in the editor.

Translated into 2 languages, including yours	
Brackets Git
Martin Zagora
0.14.24	 Integration of Git into Brackets

Translated into 7 languages, including yours	
Brackets Github Issues
Matthieu Lassalvy
1.0.1	 View current project's Github issues inside an Adobe Brackets panel

Brackets Outline List
Jan Pilzer (https://github.com/Hirse)
0.5.1	 Displays a list of the functions or definitions in the currently opened document. Works with JavaScript, CoffeeScript, CSS, SCSS, LESS, XML, HTML, SVG, Markdown and PHP. Now with Icons!

Translated into 3 languages, including yours	
Brackets SASS
Jason San Jose (https://github.com/jasonsanjose)
2.0.1-109	 ***IMPORTANT*** Read "" if you have issues removing or installing. Compiles SASS *.sass/*.scss files when changed. s styles during Live Preview. Experimental support for Quick Edit.

Brackets Terminal
Alessandro Artoni <artoale@gmail.com> (http://artoale.com)
0.3.0	 Open a terminal inside Brackets

Brackets Tools
Yasin Kuyu <yasinkuyu@gmail.com>
0.2.0	 Brackets developer tools extension

Translated into 8 languages, including yours	
Docco
Alexandru Ghiura ghalex@gmail.com (https://github.com/ghalex)
1.0.1	 Runs Docco (documentation generator) on a js file.

Extract for Brackets (Preview)
Adobe
0.7.0-1769-release	 Preview of Extract functionality inside Brackets. Extract design information and assets from a design comp via contextual code hints for CSS.

Translated into 3 languages, including yours	
FuncDocr
Ole Kröger <o.kroeger@wikunia.de>
0.8.18	 Generates JSDoc,PHPDoc annotations for your functions.

Integrated Development
@jonathanAdunlap
0.5.59	 This extension provides Brackets with integrated development capabilities like compiling, error line markers, and debugging support. Currently works with PHP, Python, Ruby, Perl, Dlang and ...

Node.js bindings
Acconut
1.4.0	 Execute node scripts and common npm commands inside Brackets.

QuickDocsJS
Ole Kröger
1.6.5	 Inline short documentation for JavaScript functions, including a summary,syntax and parameters. Docs for jQuery,NodeJS and some basic ReactJS functions.

Reasonable Comments
Peter Flynn
1.3.0	 Simple enhancement for typing block comments in Brackets: when you press Enter, the next line is automatically prefixed with a properly indented "*" (and a closing "*/" if needed). Supports all ...

WD Minimap
Brian Adams <brian@websiteduck.com> (http://www.websiteduck.com)
2.2.3	 The minimap shows a smaller version of your code at the right of the screen. It can be used to quickly scroll to a certain part of your file.

**Comment by Hirse** [comment]
I have just updated to the official 1.3 release and so far everything works fine for me.
There is no crash when I resize it in the sidebar.

I think it is a conflict with another of your extensions.
Do any of your extension change or add anything to the sidebar?

**Comment by septianw** [comment]
There's none of my plugin modify sidebar except brackets git, or maybe wd
minimap that use right side sidebar.
Pada 29 Apr 2015 17.38, "Jan Pilzer" <notifications@github.com> menulis:

**Comment by septianw** [comment]
Just find out that plugin brackets terminal v. 0.3.0 by alessandro artoni
is the culprit.
Pada 30 Apr 2015 16.10, "Septian wibisono" <asep.gelo@gmail.com> menulis:
