### ISSUE TITLE
Python support

### ISSUE THREAD

**Issue by poof86** [Hirse/brackets-outline-list#44]
I've become dependent on this extension (it's great!), but now that I have to write something in python it seems outline list doesn't work 😞

Could you please add outline support for python too?

Thank you!

**Comment by Hirse** [comment]
I will see what I can do.
In the meantime, it would be a great help if you could provide some samples of function definitions in python and a list of what you would expect to see in the outline in return.

**Comment by poof86** [comment]
I'm quite new to python, just started a few days ago, but here are the keywords that I think the outliner should pick up:
```python
def functionname(arguments):

class Classname(subclassname):
    def classfunction():
        #code
```
Python works with indentations to distinguish scope and doesn't use ';' to separate lines (weird right?).
So it's just 'def' and 'class' for now I guess. If I bump into any other keywords I'll add them here

**Comment by Hirse** [comment]
I implemented it like this right now:
![outline-python](https://cloud.githubusercontent.com/assets/2564094/10264410/e3bba780-6a0a-11e5-9f9f-bb304cd79d7c.png)
Please test it by installing from URL if you like.
