### ISSUE TITLE
Grey vertical line through outline list on the right side

### ISSUE THREAD

**Issue by op-mime** [Hirse/brackets-outline-list#52]
I've put the outline list to the right side of my brackets window. 
In non-fullscreen-mode theres a thick grey vertical line through the list.
![image](https://cloud.githubusercontent.com/assets/13900702/10962514/1fd85518-8399-11e5-956f-f1ca19b6f5f8.png)

But there's no line in fullscreen mode.
![image](https://cloud.githubusercontent.com/assets/13900702/10962520/3147d4b8-8399-11e5-99bf-3ed001cce6d0.png)

BracketsVersion: 1.5.0-16538

**Comment by Hirse** [comment]
Does that correspond to the size of your editor?
Do you have any other extensions installed that change the size on any Brackets elements?

**Comment by op-mime** [comment]
Yes it does. I've tested a bit around and found out that the overlapping line is the vertical scrollbar of the editor.

Beside _Brackets Outline List_ I've only installed _Extract for Brackets (Preview)_ (0.8.0.-1749-release) and _Markdown Preview_ (1.0.11). Both are changing the (inner) height of the editor.

**Comment by Hirse** [comment]
Do you have either of them open when this issue occurs?
I don't use *Extract*, but even when using *Markdown Preview* I don't see this.

Is the location always the same (as in same distance from the right or left edge of the outline)?
Does is change when you resize the window?
Or toggle the outline position?

**Comment by op-mime** [comment]
I've non of them open when the issue occurs.

The location is always the same if I resize the editor width. It doesn't change the relative position to the editor windows. Between the original right edge of the scrollbar and the shifted right edge is a distance of 52 px.

By the way... I'm using Windows 7 Professional SP1.

**Comment by Hirse** [comment]
So, it is "fixed" now?

**Comment by op-mime** [comment]
Yes, it is "fixed" now.
