### ISSUE TITLE
Outline is hidden after Project switch

### ISSUE THREAD

**Issue by juice** [Hirse/brackets-outline-list#54]
The Outline List disappears after switching to another Project.

In my case, i switch to a different Project with the top left Project Button.
The Outline List hides, Brackets loads the previously opened Files, but the Outline List is now gone, even if the current selected file could use the Outline List.

A switch to another file and back again is a workaround.

Outline List should check after a Project Switch if the currently opened File in the Editor uses the Outline List.

**Comment by Hirse** [comment]
Yes, it should not disappear.
Currently the outline is listening to the `activeEditorChange` and `documentSaved` events, but apparently those don't fire with the newly opened file but only without.

**Comment by Hirse** [comment]
Can't reproduce this anymore. 
Please reopen if you experience this again.
