### ISSUE TITLE
Problem with 'No distraction' mode

### ISSUE THREAD

**Issue by davidbarredo** [Hirse/brackets-outline-list#64]
When switch on the free distraction mode, with this plugin enabled, appears a black zone where the toolbar should be displayed.

<img width="698" alt="screen shot 2016-04-22 at 11 28 14" src="https://cloud.githubusercontent.com/assets/657206/14737639/5df95e82-087d-11e6-9b88-17d0edad7ad6.png">

**Comment by Hirse** [comment]
Thanks for the issue.
I have only used that mode by mistake so far, so I didn't really check when I worked on this extension.
