### ISSUE TITLE
Slowdown the screen display

### ISSUE THREAD

**Issue by Marco105** [Hirse/brackets-outline-list#66]
Hi,
I saw a very important slowdown from keyboard to display on screen with this extension active...
I use a JS file which have a lot of comment...
Is it known issue ?

**Comment by Hirse** [comment]
The extension is "parsing" the file after each save to update the outline list.
Is it a very big file with (very) long lines?

**Comment by Marco105** [comment]
Yes this a file with very long comment line, so could you find a way to escape parsing when encounter comment line in your algo (somthing like if line start with // char or /*) ?

**Comment by Hirse** [comment]
That sounds like a reasonable improvement.

In the meantime, you could check out the master branch in Git where I have experimented with using the Esprima parser.

**Comment by Marco105** [comment]
Ok, I will see!

**Comment by Hirse** [comment]
I have released a new version which uses the Espree parser to extract the outline.
I haven't done any performance tests, but please check if it work better for you.

**Comment by Marco105** [comment]
Hi, I saw difference with 320 line files and only 45 lines no commented... WORKS VERY FINE NOW !
Thank's so much !

**Comment by Hirse** [comment]
Great, I'll close this then.
