### ISSUE TITLE
PHP class support

### ISSUE THREAD

**Issue by tonoslav** [Hirse/brackets-outline-list#67]
Hello, 

it should be awesome if you could implement **PHP objects support** to show outline of whole classes for example, something like code explorer in other softwares.
For example:
- ClassName [extends Class] 
  - $prop1
  - $prop2
  - $prop3
  - .... (methods)
- ClassName2 [extends Class] 
  - $prop1
  - $prop2
  - $prop3
  - .... (methods)

**Comment by Hirse** [comment]
I agree that would be nice.
Unfortunately I have not found a tool that extracts these information for me, so the extension is using a custom parser/lexer which @yfwz100 contributed.
Maybe you want to look into extending it with support for classes (or convince him to do so 😉 ).

**Comment by tonoslav** [comment]
@Hirse It would be awesome if @yfwz100 could do that for us, I can try it but I don't have enough time.
I'm really new with Brackets but I will try it soon if nobody give us any solution sooner.

**Comment by yfwz100** [comment]
I am glad if anyone could help :smile . Actually I am busy preparing my graduate project so I may not have enough time for this. 

ps: The parser has been able to deal with classes/namespaces. However, if you want to make a tree view, just modify the state array and make a hierarchical list with indent in each items(properties/functions) that belongs to a class.

**Comment by Hirse** [comment]
Thanks for the hint @yfwz100 and good luck with your project.
