### ISSUE TITLE
support Es6

### ISSUE THREAD

**Issue by TWOWhite** [Hirse/brackets-outline-list#71]
Hello,i found that the extension can not identify ECMAScript 6.i really hope it can support ES6,this extension is very good.
thanks

**Comment by Hirse** [comment]
Thanks, I am happy that you like it.

Could you please provide a concrete example of code, which is not supported and the expected result?

**Comment by Hirse** [comment]
Closing, as there hasn't been any response.
Please try the latest version and reopen if you are still experiencing problems.
