### ISSUE TITLE
brackets-outline-list always open when I start Brackets

### ISSUE THREAD

**Issue by ruiborgespaninho** [Hirse/brackets-outline-list#72]
**Details about your environment**

* **Brackets Version: 1.8** 
* **Brackets Outline List Version: 1.0.0-alpha** 

**What did you do? Please include the actual source code causing the issue.**

I start brackets editor

**What did you expect to happen? How did you expect the Outline to look?**

Outline extension should be closed

**What actually happened? How did the Outline actually look?**

Outline extension is open and empty

**Note**

Outline extension is displayed beside the sidebar as a panel

![image](https://cloud.githubusercontent.com/assets/23142516/20608064/2f780a80-b27e-11e6-8fd6-32eae3d5a5af.png)

**Comment by Hirse** [comment]
Do you have any files open?
Does it stay open when you open and close any file?

**Comment by ruiborgespaninho** [comment]
It open when I start Bracket with or without files. When I open a file, the extension stay opened. I need to click two times on the extension icon, to close the panel
