### ISSUE TITLE
Misinterpreting embedded html 'class' in PHP

### ISSUE THREAD

**Issue by acmp** [Hirse/brackets-outline-list#73]
The issue I'm having is that Outline is parsing my PHP, seeing the word 'class' in some embedded html and thinking it is a class declaration, so it starts to build prefixes for the functions. This results in _very_ long function names, usually wider than my monitor can display, as it simply seems to concatenate every word after 'class' 

I suspect the parser is not recognizing that 'class' is a text string. In fact in the file I'm currently looking at there are no class definitions at all as all the classes are in external files.

Outline didn't behave like the previously. I am unsure if this behavior started after an update, of when I added some legitimate class calls. The issue does however appear to affect other projects that do not use class calls. 

Windows 10

* **Brackets Version:** 1.8.0-17108
* **Brackets Outline List Version:** 1.0.0-alpha.0

**What did you do? Please include the actual source code causing the issue.**
in my PHP

```php
function _flow(){/*Place holder*/}
switch(isset($something){
  case ($something='stuff'):
    $pagedefault['content'].='<ul class="reqhead" >'.$nr.'</ul>';
  ...
}
...
function ProcessAction ($vars){...}
```

**What did you expect to happen? How did you expect the Outline to look?**
_flow()
ProcessAction($vars)

**What actually happened? How did the Outline actually look?**
_flow()
reqhead::ul::ProcessAction($vars)

With all other extensions disabled the behavior is the same

**Comment by Hirse** [comment]
Thanks for the detailed report.
This seems to be caused by an error in the new PHP parser, which was added in the latest update.

**Comment by romanran** [comment]
I've got the same issue which renders the 1.0 unusable, html breaks function detection. I had to downgrade to 0.7. which works fine.

**Comment by Hirse** [comment]
Please check the latest version, which contains some fixes for PHP.
