### ISSUE TITLE
ES6 class functions support

### ISSUE THREAD

**Issue by yngve-sk** [Hirse/brackets-outline-list#79]
ES6 class functions show up as anonymous functions in the outline. It has been super helpful when not using ES6 classes and I would love for this to work on ES6 classes.

I.e: 
`
class test {
a(arg1, arg2, arg3) { ... }
}
`

will show as: function(arg1, arg2, arg3) in the outline. 

![screen shot 2017-01-28 at 5 39 53 pm](https://cloud.githubusercontent.com/assets/11595637/22398103/d7d9b892-e580-11e6-8df2-6545c63dbf39.png)

It seems the parser isn't picking up on the ES6 class name. In JSParser.js in the _visit function the Node has an id of null...

**Comment by Hirse** [comment]
Thanks for this bug report.
Could you please add the version information as requested in the issue template?

**Comment by yngve-sk** [comment]
**Details about your environment**
OS: Mac OSX sierra (10.12.2)
JS version: ES6

* **Brackets Version:** 
Release 1.8 build 1.8.0-17108 (alf_localization_release_1.8 3af64fae4) 

* **Brackets Outline List Version:** 
v1.0.0-alpha.1

Hope this helps!

**Comment by Hraesvelg** [comment]
hi,

i have the same problem, the outline view doesn't support ES6 !

Brackets : 1.8.0-17108
Outline : 1.0.0-alpha.0

**Comment by Hirse** [comment]
@yngve-sk, @Hraesvelg feel free to install the extension from source and see if it is fixed.
I'll release the fix after solving a few other issues.
