### ISSUE TITLE
Python functions with **kwargs argument are not listed in the outline

### ISSUE THREAD

**Issue by gittar** [Hirse/brackets-outline-list#96]
**Details about your environment**
Ubuntu 16.04 LTS
* **Brackets Version:** 
Release 1.9.0-17312
* **Brackets Outline List Version:** 
1.2.0

**What did you do? Please include the actual source code causing the issue.**
```python
def whoami(**kwargs):
    return inspect.stack()[1][3]
```

**What did you expect to happen? How did you expect the Outline to look?**
I expected the function `whoami` to appear in the outline list.

**What actually happened? How did the Outline actually look?**
It did not appear in the outline. Others were listed ok.

Remark: The problem seems to be the `**kwargs` syntax. The following variants appear correctly in the outline list:
```python
def whoami():
    return inspect.stack()[1][3]

def whoami(dummy):
    return inspect.stack()[1][3]
```

**Comment by Hirse** [comment]
Sorry for the late response. The fix should be in the next release.
