### ISSUE TITLE
Python functions with default arguments are not listed in the outline

### ISSUE THREAD

**Issue by gittar** [Hirse/brackets-outline-list#97]
**Details about your environment**
Ubuntu 16.04 LTS
* **Brackets Version:** 
Release 1.9.0-17312
* **Brackets Outline List Version:** 
1.2.0

**What did you do? Please include the actual source code causing the issue.**

```python
# returns the name of the current function
def whoami(dummy=0):
    return inspect.stack()[1][3]
```

**What did you expect to happen? How did you expect the Outline to look?**
I expected the function `whoami` to appear in the outline list.

**What actually happened? How did the Outline actually look?**
The function did not appear in the outline. Others were listed ok.

Remark: The problem seems to be the default argument syntax `(dummy=0)`. The following variants appear correctly in the outline list:
```python
# returns the name of the current function
def whoami():
    return inspect.stack()[1][3]

def whoami(dummy):
    return inspect.stack()[1][3]
```

**Comment by Hirse** [comment]
I am sorry for the late reply, but it works fine for me with the default argument:
![image](https://user-images.githubusercontent.com/2564094/29619297-104fb48c-881b-11e7-846b-091b7af99123.png)

**Comment by Hirse** [comment]
This was in fact fixed in https://github.com/Hirse/brackets-outline-list/pull/90 for 1.1.0

**Comment by gittar** [comment]
Please try again with a floating point default arg, e.g. (dummy=1.0). Recently I observed that only that did not work.
 


Gesendet: Mittwoch, 23. August 2017 um 15:53 Uhr
Von: "Jan Pilzer" <notifications@github.com>
An: Hirse/brackets-outline-list <brackets-outline-list@noreply.github.com>
Cc: "Bernd Fritzke" <gituser@pop.ms>, Author <author@noreply.github.com>
Betreff: Re: [Hirse/brackets-outline-list] Python functions with default arguments are not listed in the outline (#97)


I am sorry for the late reply, but it works fine for me with the default argument:

**Comment by Hirse** [comment]
Please see the latest release, that should solve it.
