### ISSUE TITLE
No working in Vue File！

### ISSUE THREAD

**Issue by Mini256** [Hirse/brackets-outline-list#98]
**Details about your environment**

* **Brackets Version:** ALL
* **Brackets Outline List Version:** ALL

**What did you expect to happen? How did you expect the Outline to look?**
brackets-outline-list is no working in *.vue file,hope coming soon!

**Comment by Hirse** [comment]
Please try the latest release. It should show an outline for Vue Component Files like for HTML.

**Comment by Mini256** [comment]
So quickly and good Work! but it could be better,It has already worked into the <template> label,but it dosen't show an outline for  the <style> label and <script> label.

I think you should  make a fold for the more and more outlines to classify them.

**Comment by Hirse** [comment]
Do you mean it misses entries for the `style` and `script` tags or for the content inside? The first one is a bug, the second a missing (and rather hard) new feature.
